version: "3"

services:
    mongodb:
        image: mongo:5.0
        restart: always
    
    app:
        build: ./
        depends_on:
            - mongodb
        ports:
            - 3000:3000
            - 8080:8080
        environment:
            MONGO_URL: mongodb://mongodb:27017/tms
            PORT: 3000
            SERVER_PORT: 8080
        volumes:
            - ./:/app
        command: npm run dev